#!/usr/bin/env bash

set -e

default_reviewers=(
  "aanzolaavila"
  "jcmnavia"
  "jencina-treble"
  "jmz7v"
  "Sborzguilherme"
  "spsaaibi"
  "volcinschi"
  "Yefri97"
  "Zekkenn"
)

function get_current_repo() {
  local repo_name
  if [ -d ".git" ]; then
    repo_name="$(git config --get remote.origin.url | cut -d ':' -f 2)"
  elif [ -d ".jj" ]; then
    repo_name="$(jj git remote list | head -n 1 | cut -d ':' -f 2)"
  else
    echo "No git nor jujutsu repo detected"
    exit 1
  fi

  # stripping .git suffix
  echo "${repo_name%%.git}"
}

function get_current_prs() {
  local repo="${1}"
  gh pr list \
    --repo "${repo}" \
    --author @me \
    --json "url,isDraft" \
    --jq '.[] | select(.isDraft == false) | .url'
}

function get_current_reviewers() {
  # Get current reviewers, people that already reviewed and assignees
  local repo="${1}"
  local pr="${2}"

  gh pr view \
    "${pr}" \
    --repo "${repo}" \
    --json 'reviewRequests,reviews,assignees' \
    --jq '[.reviewRequests[] | .login] + [.reviews[] | .author.login] + [.assignees[] | .login] | unique | .[]'
}

function skip_current_reviewers() {
  local current_reviewers="${1}"

  comm -23 \
    <(printf "%s\n" "${default_reviewers[@]}" | sort) \
    <(echo "${current_reviewers}" | sort)
}

function assign_reviewers() {
  local pr="${1}"
  local reviewers="${2}"

  reviewer_args=()
  while IFS=$'\n' read -r reviewer; do
    if [ "${reviewer}" == "" ]; then
      continue
    fi

    arg="--add-reviewer ${reviewer}"
    reviewer_args+=("${arg}")
  done <<<"${reviewers}"

  reviewers_str="${reviewer_args[*]}"
  if [ "${reviewers_str}" != "" ]; then
    gh pr edit "${pr}" ${reviewers_str}
  else
    echo "No reviewers missing to add"
  fi
}

repo=$(get_current_repo)
prs=$(get_current_prs "${repo}")

while IFS=$'\n' read -r pr; do
  current_reviewers=$(get_current_reviewers "${repo}" "${pr}")
  missing_reviewers=$(skip_current_reviewers "${current_reviewers}")
  printf "Assigning missing reviewers for PR '%s':\n%s" "${pr}" "${missing_reviewers}"
  assign_reviewers "${pr}" "${missing_reviewers}"
done <<<"${prs}"
