#!/usr/bin/env bash
# based on ThePrimeagen's sessionizer https://github.com/ThePrimeagen/.dotfiles/blob/602019e902634188ab06ea31251c01c1a43d1621/bin/.local/scripts/tmux-sessionizer
# and based on https://github.com/thoughtbot/dotfiles/blob/main/bin/tat

if [[ $# -eq 0 ]]; then
  selected="${PWD}"
else
  selected="${1}"
fi

session_name="$(basename "$selected" | tr . _)"

not_in_tmux() {
  [ -z "$TMUX" ]
}

session_exists() {
  tmux has-session -t "=$session_name"
}

create_detached_session() {
  (TMUX='' tmux new-session -Ad -s "$session_name")
}

create_if_needed_and_attach() {
  if not_in_tmux; then
    tmux new-session -As "$session_name" -c "$selected"
  else
    if ! session_exists; then
      create_detached_session
    fi
    tmux switch-client -t "$session_name"
  fi
}

create_if_needed_and_attach
