#!/usr/bin/env bash

selected=$(fd --type d -H '.git$' --no-ignore ~/code ~/Documents | sed 's/\/.git\///' | fzf)

if [[ -z "${selected}" ]]; then
  exit 0
fi

printf "Selected directory: %s\n" "${selected}"

tat "${selected}"
