#!/usr/bin/env bash

set -e

function update_k8s_context() {
  local profile="${1}"
  local region="${2}"
  local cluster_name="${3}"

  aws --profile "${profile}" eks update-kubeconfig --region "${region}" --name "${cluster_name}" --alias "${cluster_name}"
}

function update_dev_k8s_context() {
  local profile="flex-admin"
  aws-select "${profile}"

  update_k8s_context "${profile}" "us-west-2" "sandbox-1"
  update_k8s_context "${profile}" "us-west-2" "hitl-1"
  update_k8s_context "${profile}" "us-west-2" "gen-dev-1"
  update_k8s_context "${profile}" "us-west-2" "na-dev-1"
  update_k8s_context "${profile}" "eu-central-1" "eu-dev-1"
  update_k8s_context "${profile}" "ap-northeast-1" "ap-dev-1"
}

function update_prod_k8s_context() {
  local profile="prod"
  aws-select "${profile}"

  update_k8s_context "${profile}" "us-west-2" "na-prod-1"
  update_k8s_context "${profile}" "us-east-1" "na-prod-2"
  update_k8s_context "${profile}" "eu-central-1" "eu-prod-1"
  update_k8s_context "${profile}" "eu-west-1" "eu-prod-2"
  update_k8s_context "${profile}" "ap-northeast-1" "ap-prod-1"
}

current_ctx=$(kubectl config current-context)

update_dev_k8s_context
update_prod_k8s_context

kubectl config use-context "${current_ctx}"
